version: 0.2

phases:
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/c2s9r9y6
    - REPOSITORY_URI=public.ecr.aws/c2s9r9y6/aws_ecr_repo_pub_batchfifteen-tf
    - IMAGE_TAG=latest
  build:
    commands:
    - echo Building the Docker image...
    - docker build -t $REPOSITORY_URI:latest .

  post_build:
    commands:
    - echo Pushing the Docker images...
    - docker push $REPOSITORY_URI:latest
    - echo Writing image definitions file...
    - printf '[{"name":"myflaskcontainer","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
    - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json
